
* Setup
** ESP8266 arduino
   We are using the ESP8266 for the node processor, which can be
   programmed using the Arduino framework.

   To set this up, you can follow the steps at the following website:
   https://github.com/esp8266/Arduino

   Or just follow the following simple steps (paraphrased from above):
   - Install the latest arduino from the [[https://www.arduino.cc/][Arduino Website]]
   - Start Arduino and open Preferences window.
   - Enter
     =http://arduino.esp8266.com/stable/package_esp8266com_index.json=
     into Additional Board Manager URLs field. You can add multiple
     URLs, separating them with commas.
   - Open Boards Manager from =Tools > Board= menu and install esp8266
     platform (and don't forget to select your ESP8266 board from
     =Tools > Board= menu after installation).
** MQTT
   This project uses the =MQTT= publish/subscribe protocol to send
   messages between the nodes and the server (bigbro).

   To install the library, you need to download the latest =PubSubClient=
   as a zip from https://github.com/knolleary/pubsubclient/releases.

   Then add it to the Arduino IDE by navigating to
   =Sketch > Include Library > Add .ZIP Library= and selecting the
   downloaded zip.      If there were an automated way to do this I would. But
   there isn't. Get your game together Arduino. Sheesh.

** NRF24L01
   To be determined...

* Hardware
  The hardware for the node is rather simple, all it is is an =ESP-12=
  module and an =NRF24L01= module.

  To prototype this, connect it up as follows:
  | ESP8266 GPIO name | ESP-12 pin | NodeMCU DevKit v1 pin | Usage (on NRF24L01 module) |
  | GPIO0             |          4 |                    D3 | IRQ                        |
  | GPIO12            |         14 |                    D6 | MISO                       |
  | GPIO13            |         15 |                    D7 | MOSI                       |
  | GPIO14            |         13 |                    D5 | SCK                        |
  | GPIO15            |         15 |                    D8 | CS                         |
  | GPIO16            |         12 |                    D0 | CE                         |
